"use client";

import "./globals.css";

import Providers from "./providers";
import Header from "@/app/components/common/Header/Header";

// export const metadata = {
//   title: "Create Next App",
//   description: "Generated by create next app",
// };

export default function RootLayout({ children }) {
  return (
    <Providers>
      <html lang="en">
        <body suppressHydrationWarning={true}>
          <Header />
          {children}
        </body>
      </html>
    </Providers>
  );
}
